In [1]:
import numpy as np

In [25]:
seqa = 'ALH'
seqb = 'AGH'

class NW():
    def __init__(
            self, seqa:str, seqb:str, 
            match, mismatch, gap
    ):
        self.seqa = seqa
        self.seqb = seqb
        self.match_score = match
        self.mismatch_score = mismatch
        self.gap_score = gap
        self.matrix = np.zeros((len(seqa)+1, len(seqb)+1))
        self.matrix.fill(np.inf)
        self.matrix[:, 0] = [self.gap_score * i for i in range(self.matrix.shape[0])]
        self.matrix[0, :] = [self.gap_score * j for j in range(self.matrix.shape[1])]

                
    def _scoring(self):
        for row_idx, i in enumerate(self.matrix):
            for col_idx, j in enumerate(i):
                
                if j != np.inf:
                    pass
                else:
                    '''
                    lt: right top (diagonal)
                    lt_: rt + match or mismatch
                    rb: right bottom
                    lt: left top
                    '''
                    lt = self.matrix[row_idx-1, col_idx-1]
                    lt_ = lt + self.match_score if self.seqa[row_idx-1] == self.seqb[col_idx-1] else lt + self.mismatch_score
                    
                    lb = self.matrix[row_idx, col_idx-1]
                    rt = self.matrix[row_idx-1, col_idx]

                    score = np.max([lt_, lb+self.gap_score, rt+self.gap_score])

                    self.matrix[row_idx, col_idx] = score

        return self.matrix
    
    def _traceback(self,):
        '''
        Initialize traceback procedure: 
        row: the row coordinate of the current value
        col: the column coordinate of the current value
        '''

        seqa_output, seqb_output = [], []

        row = self.matrix.shape[0] - 1
        col = self.matrix.shape[1] - 1

        traceback_list = []
        traceback = self.matrix[row, col]
        traceback_list.append(traceback)
        
        #seqa_output.append(self.seqa[row-1])
        #seqb_output.append(self.seqb[col-1])

        while row > 0 or col > 0:
            '''
            window_state: score as key, coordinates(tuple) as value
            lb: left bottom
            lt: left top
            rt: right top
            '''
            window_state = {}
            lb = self.matrix[row, col-1]
            lt = self.matrix[row-1, col-1]
            rt = self.matrix[row-1, col]
            window_state[lb] = (row, col-1)
            window_state[lt] = (row-1, col-1)
            window_state[rt] = (row-1, col)

            #print(window_state)

            traceback = max(lb, lt, rt)
            traceback_list.append(traceback)

            # How N&W gets rid of local optimum

            #print(f'row: {row}')
            print(traceback)
            if traceback == lt:
                seqa_output.append(self.seqa[row-1])
                seqb_output.append(self.seqb[col-1])
                print(f'{traceback}: {self.seqa[row-1]}')
                row = window_state[traceback][0]
                col = window_state[traceback][1]
                continue
                
            elif traceback == lb:
                seqa_output.append('-')
                #seqb_output.append(self.seqb[col-1])
                row = window_state[traceback][0]
                col = window_state[traceback][1]
                continue
            else:
                #seqa_output.append(self.seqa[row-1])
                seqb_output.append('-')
                row = window_state[traceback][0]
                col = window_state[traceback][1]
                continue

                
        
        return seqa_output, seqb_output

    
    def align(self):
        score_matrix = self._scoring()
        print(score_matrix)
        seqa_output, seqb_output = self._traceback()
        return seqa_output, seqb_output

            

    
nw = NW(seqa, seqb, 1, -1, -1)
m,n = nw.align()
print(m, n)


[[ 0. -1. -2. -3.]
 [-1.  1.  0. -1.]
 [-2.  0.  0. -1.]
 [-3. -1. -1.  1.]]
0.0
0.0: H
1.0
1.0: L
0.0
0.0: A
['H', 'L', 'A'] ['H', 'G', 'A']


In [26]:
seqa1 = 'AEGHK'
seqb1 = 'AELHK'
nw1 = NW(seqa1, seqb1, 1, -1, 0)
m1 = nw1.align()
print(m1)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3.]
 [0. 1. 2. 2. 3. 4.]]
3.0
3.0: K
3.0
2.0
2.0: H
2.0
2.0: G
2.0
2.0
1.0
1.0: E
1.0
0.0
0.0: A
1.0
1.0
1.0
1.0
1.0
0.0


IndexError: string index out of range

In [ ]:
seqa = 'ALH'
seqb = 'AGH'

class NW():
    def __init__(
            self, seqa:str, seqb:str, 
            match, mismatch, gap
    ):
        self.seqa = seqa
        self.seqb = seqb
        self.match_score = match
        self.mismatch_score = mismatch
        self.gap_score = gap
        self.matrix = np.zeros((len(seqa)+1, len(seqb)+1))
        self.matrix.fill(np.inf)
        self.matrix[:, 0] = [self.gap_score * i for i in range(self.matrix.shape[0])]
        self.matrix[0, :] = [self.gap_score * j for j in range(self.matrix.shape[1])]

                
    def _scoring(self):
        for row_idx, i in enumerate(self.matrix):
            for col_idx, j in enumerate(i):
                
                if j != np.inf:
                    pass
                else:
                    '''
                    lt: right top (diagonal)
                    lt_: rt + match or mismatch
                    rb: right bottom
                    lt: left top
                    '''
                    lt = self.matrix[row_idx-1, col_idx-1]
                    lt_ = lt + self.match_score if self.seqa[row_idx-1] == self.seqb[col_idx-1] else lt + self.mismatch_score
                    
                    lb = self.matrix[row_idx, col_idx-1]
                    rt = self.matrix[row_idx-1, col_idx]

                    score = np.max([lt_, lb+self.gap_score, rt+self.gap_score])

                    self.matrix[row_idx, col_idx] = score

        return self.matrix
    
    def _traceback(self,):
        seqa_output, seqb_output = [], []
        row = self.matrix.shape[0] - 1
        col = self.matrix.shape[1] - 1

        while row > 0 or col > 0:

            # How N&W gets rid of local optimum

            print(f'row: {row}, col: {col}')
            current_score = self.matrix[row, col]

            if row > 0 and col >0:
                #match_val = self.match_score if self.seqa[row-1] == self.seqb[col-1] else self.mismatch_score
                match_val = self.match_score if self.seqa[row-1] == self.seqb[col-1] else self.mismatch_score
                print(match_val)
                if current_score == self.matrix[row-1, col - 1] + match_val:
                    seqa_output.append(self.seqa[row-1])
                    seqb_output.append(self.seqb[col-1])
                    
                    row -= 1
                    col -= 1
                    continue
                
            if col>0 and current_score == self.matrix[row, col - 1] + self.gap_score:
                seqa_output.append('-')
                seqb_output.append(self.seqb[col-1])
                col -= 1
                continue

            if row > 0 and current_score == self.matrix[row - 1, col] + self.gap_score:
                
                seqa_output.append(self.seqa[row-1])
                seqb_output.append('-')
                row -= 1
                
                continue

                
        seqa_output.reverse(), seqb_output.reverse()
        return seqa_output, seqb_output
    
    def align(self):
        score_matrix = self._scoring()
        print(score_matrix)
        seqa_output, seqb_output = self._traceback()
        return seqa_output, seqb_output

            

    
nw = NW(seqa, seqb, 1, -1, -1)
m,n = nw.align()
print(m, n)

[[ 0. -1. -2. -3.]
 [-1.  1.  0. -1.]
 [-2.  0.  0. -1.]
 [-3. -1. -1.  1.]]
row: 3, col: 3
1
row: 2, col: 2
-1
row: 1, col: 1
1
['A', 'L', 'H'] ['A', 'G', 'H']


In [ ]:
m

['A', 'L', 'H']

In [ ]:
seqa1 = 'AEGHK'
seqb1 = 'AELHK'
nw1 = NW(seqa1, seqb1, 1, -1, 0)
m1, n1 = nw1.align()
print(m1)
print(n1)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3.]
 [0. 1. 2. 2. 3. 4.]]
row: 5, col: 5
1
row: 4, col: 4
1
row: 3, col: 3
-1
row: 3, col: 2
-1
row: 2, col: 2
1
row: 1, col: 1
1
['A', 'E', 'G', '-', 'H', 'K']
['A', 'E', '-', 'L', 'H', 'K']


In [ ]:
seqa = 'ALH'
seqb = 'AGH'

class NW():
    def __init__(
            self, seqa:str, seqb:str, 
            match, mismatch, gap
    ):
        self.seqa = seqa
        self.seqb = seqb
        self.match_score = match
        self.mismatch_score = mismatch
        self.gap_score = gap
        self.matrix = np.zeros((len(seqa)+1, len(seqb)+1))
        self.matrix.fill(np.inf)
        self.matrix[:, 0] = [self.gap_score * i for i in range(self.matrix.shape[0])]
        self.matrix[0, :] = [self.gap_score * j for j in range(self.matrix.shape[1])]

                
    def _scoring(self):
        for row_idx, i in enumerate(self.matrix):
            for col_idx, j in enumerate(i):
                
                if j != np.inf:
                    pass
                else:
                    '''
                    lt: right top (diagonal)
                    lt_: rt + match or mismatch
                    rb: right bottom
                    lt: left top
                    '''
                    lt = self.matrix[row_idx-1, col_idx-1]
                    lt_ = lt + self.match_score if self.seqa[row_idx-1] == self.seqb[col_idx-1] else lt + self.mismatch_score
                    
                    lb = self.matrix[row_idx, col_idx-1]
                    rt = self.matrix[row_idx-1, col_idx]

                    score = np.max([lt_, lb+self.gap_score, rt+self.gap_score])

                    self.matrix[row_idx, col_idx] = score

        return self.matrix
    
    def _traceback(self,):
        seqa_output, seqb_output = [], []
        row = self.matrix.shape[0] - 1
        col = self.matrix.shape[1] - 1

        while row > 0 or col > 0:

            # How N&W gets rid of local optimum

            window_state = {}
            lb = self.matrix[row, col-1]
            lt = self.matrix[row-1, col-1]
            rt = self.matrix[row-1, col]
            window_state[lb] = (row, col-1)
            window_state[rt] = (row-1, col)
            window_state[lt] = (row-1, col-1)
            print(f'windowstate: {window_state}')
            current_score = self.matrix[row, col]
            print(f'currentscore: {current_score}')

            if row > 0 and col >0:
                #match_val = self.match_score if self.seqa[row-1] == self.seqb[col-1] else self.mismatch_score
                match_val = self.match_score if self.seqa[row-1] == self.seqb[col-1] else self.mismatch_score
                print(match_val)
                if current_score == lt + match_val:
                    seqa_output.append(self.seqa[row-1])
                    seqb_output.append(self.seqb[col-1])
                    row = window_state[lt][0]
                    col = window_state[lt][1]
                    continue

            if col>0 and current_score == lb + self.gap_score:
                seqa_output.append('-')
                seqb_output.append(self.seqb[col-1])
                row = window_state[lt][0]
                col = window_state[lt][1]
                continue

            if row>0 and current_score == rt + self.gap_score:
                print(f'right top: {rt}')
                seqa_output.append(self.seqa[row-1])
                seqb_output.append('-')
                row = window_state[lt][0]
                col = window_state[lt][1]
                continue

        seqa_output.reverse(), seqb_output.reverse()
        return seqa_output, seqb_output

    def align(self):
        score_matrix = self._scoring()
        print(score_matrix)
        seqa_output, seqb_output = self._traceback()
        return seqa_output, seqb_output


    
nw = NW(seqa, seqb, 1, -1, -1)
m,n = nw.align()
print(m, n)

[[ 0. -1. -2. -3.]
 [-1.  1.  0. -1.]
 [-2.  0.  0. -1.]
 [-3. -1. -1.  1.]]
windowstate: {-1.0: (2, 3), 0.0: (2, 2)}
currentscore: 1.0
1
windowstate: {0.0: (1, 2), 1.0: (1, 1)}
currentscore: 0.0
-1
windowstate: {-1.0: (0, 1), 0.0: (0, 0)}
currentscore: 1.0
1
['A', 'L', 'H'] ['A', 'G', 'H']


In [3]:
seqa1 = 'AEGHK'
seqb1 = 'AELHK'
nw1 = NW(seqa1, seqb1, 1, -1, 0)
m1, n1 = nw1.align()
print(m1)
print(n1)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 2. 3. 3.]
 [0. 1. 2. 2. 3. 4.]]
windowstate: {3.0: (4, 4)}
currentscore: 4.0
1
windowstate: {2.0: (3, 3)}
currentscore: 3.0
1
windowstate: {2.0: (2, 2)}
currentscore: 2.0
-1
windowstate: {1.0: (1, 1)}
currentscore: 2.0
1
windowstate: {0.0: (0, 0)}
currentscore: 1.0
1
['A', 'E', '-', 'H', 'K']
['A', 'E', 'L', 'H', 'K']


## **Q: How N&W gets rid of local optimum**